<template>
  <div>
    <PageHeader title="交付通知" description="供应商提交发货与预计到达信息，采购方据此安排收货；每个通知关联订单。">
      <template #actions><el-button v-if="auth.role === 'SUPPLIER'" :icon="DataAnalysis" @click="router.push('/ai-parse')">解析到货通知</el-button><el-button v-if="auth.role === 'SUPPLIER'" type="primary" :icon="Plus" @click="openCreate">新建通知</el-button></template>
    </PageHeader>
    <section class="surface delivery-table"><div class="toolbar"><el-input v-model="keyword" clearable placeholder="搜索通知号、订单号或供应商" :prefix-icon="Search" /><el-select v-model="statusFilter" clearable placeholder="全部状态" style="width: 145px"><el-option v-for="item in statusOptions" :key="item.value" :label="item.label" :value="item.value" /></el-select><span class="toolbar-spacer"></span><span class="toolbar-meta">{{ filtered.length }} 条通知</span><el-button :icon="Refresh" :loading="loading" @click="load">刷新</el-button></div><div v-if="errorMessage" class="inline-error"><WarningFilled />{{ errorMessage }}</div><div v-if="loading && !deliveries.length" class="table-loading"><div v-for="i in 3" :key="i" class="skeleton" style="height: 45px"></div></div><div v-else-if="!filtered.length"><EmptyState title="暂无交付通知" :description="emptyDescription" :action-text="emptyActionText" @action="handleEmptyAction" /></div><div v-else class="table-wrap"><el-table :data="filtered" stripe><el-table-column prop="noticeNo" label="通知号" width="170" /><el-table-column prop="orderNo" label="关联订单" width="170" /><el-table-column prop="supplierName" label="供应商" min-width="180" /><el-table-column prop="createdAt" label="创建时间" width="180" /><el-table-column prop="eta" label="预计到达" width="170" /><el-table-column label="申报数量" width="115" align="right"><template #default="scope"><span class="number">{{ scope.row.quantity.toLocaleString() }}</span></template></el-table-column><el-table-column label="状态" width="120"><template #default="scope"><StatusBadge :label="statusMeta(scope.row.status).label" :tone="statusMeta(scope.row.status).tone" /></template></el-table-column><el-table-column prop="note" label="备注" min-width="190" show-overflow-tooltip /><el-table-column label="操作" width="280" fixed="right"><template #default="scope"><el-button link type="primary" @click="showDetail(scope.row)">查看</el-button><el-button v-if="scope.row.status === 'DRAFT' && auth.role === 'SUPPLIER'" link type="primary" @click="transitionNotice(scope.row, 'SUBMIT')">提交</el-button><el-button v-if="scope.row.status === 'SUBMITTED' && auth.role === 'SUPPLIER'" link type="primary" @click="transitionNotice(scope.row, 'DISPATCH')">发运</el-button><el-button v-if="scope.row.status === 'IN_TRANSIT' && auth.role === 'BUYER'" link type="primary" @click="transitionNotice(scope.row, 'ARRIVE')">标记到达</el-button></template></el-table-column></el-table></div></section>
    <el-dialog v-model="dialogVisible" title="新建交付通知" width="520px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="form-grid"><el-form-item label="关联订单" prop="orderId"><el-select v-model="form.orderId" filterable style="width:100%" placeholder="选择已确认/待发货订单" @change="onOrderChange"><el-option v-for="item in eligibleOrders" :key="item.id" :label="`${item.orderNo} · ${item.supplierName}`" :value="item.id" /></el-select></el-form-item><el-form-item label="订单行" prop="orderItemId"><el-select v-model="form.orderItemId" filterable style="width:100%" placeholder="选择订单行"><el-option v-for="item in orderItems" :key="String(item.id)" :label="`${item.materialCode || item.materialName || item.id} · ${item.quantity ?? '—'}`" :value="String(item.id)" /></el-select></el-form-item><el-form-item label="申报数量" prop="quantity"><el-input-number v-model="form.quantity" :min="0.0001" :precision="4" style="width:100%" /></el-form-item><el-form-item label="预计到达" prop="eta"><el-date-picker v-model="form.eta" value-format="YYYY-MM-DD" type="date" style="width:100%" /></el-form-item><el-form-item label="承运商"><el-input v-model="form.carrierName" placeholder="可选" /></el-form-item><el-form-item label="运单号"><el-input v-model="form.trackingNo" placeholder="可选" /></el-form-item></div><div class="inline-note">创建后通知为 DRAFT；供应商需继续提交并发运，采购人员再标记到达。</div></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">创建通知</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { DataAnalysis, Plus, Refresh, Search, WarningFilled } from '@element-plus/icons-vue'
import { useRouter } from 'vue-router'
import PageHeader from '@/components/PageHeader.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import EmptyState from '@/components/EmptyState.vue'
import { useAuthStore } from '@/stores/auth'
import { apiList, apiMutate, apiRequest, extractApiError } from '@/services/api'
import { demoDeliveries } from '@/services/demo'
import { mapDelivery, mapOrder } from '@/services/mappers'
import type { DeliveryNotice, PurchaseOrder } from '@/types'

interface OrderItem { id: string | number; materialCode?: string; materialName?: string; quantity?: number }
interface OrderDetail extends PurchaseOrder { items?: OrderItem[] }
const router = useRouter(); const auth = useAuthStore(); const deliveries = ref<DeliveryNotice[]>([]); const orders = ref<PurchaseOrder[]>([]); const orderItems = ref<OrderItem[]>([]); const keyword = ref(''); const statusFilter = ref(''); const loading = ref(false); const saving = ref(false); const errorMessage = ref(''); const dialogVisible = ref(false); const selected = ref<DeliveryNotice>(); const formRef = ref<FormInstance>()
const form = reactive({ orderId: '', orderItemId: '', eta: '', quantity: 1, carrierName: '', trackingNo: '', note: '' }); const rules: FormRules = { orderId: [{ required: true, message: '请输入关联订单 ID', trigger: 'blur' }], orderItemId: [{ required: true, message: '请输入订单行 ID', trigger: 'blur' }], eta: [{ required: true, message: '请选择预计到达日期', trigger: 'change' }], quantity: [{ required: true, message: '请输入申报数量', trigger: 'change' }] }; const statusOptions = [{ value: 'DRAFT', label: '草稿' }, { value: 'SUBMITTED', label: '已提交' }, { value: 'IN_TRANSIT', label: '运输中' }, { value: 'ARRIVED', label: '已到达' }, { value: 'EXCEPTION', label: '异常' }, { value: 'CANCELLED', label: '已取消' }]
const filtered = computed(() => deliveries.value.filter((item) => (!statusFilter.value || item.status === statusFilter.value) && (!keyword.value || `${item.noticeNo}${item.orderNo}${item.supplierName}`.toLowerCase().includes(keyword.value.toLowerCase()))))
const eligibleOrders = computed(() => orders.value.filter((item) => ['CONFIRMED', 'PENDING_SHIPMENT', 'PARTIALLY_RECEIVED'].includes(item.status)))
const hasFilters = computed(() => Boolean(keyword.value || statusFilter.value))
const emptyDescription = computed(() => hasFilters.value ? '当前筛选条件下没有匹配记录。' : auth.role === 'SUPPLIER' ? '可以为已确认或待发货订单创建第一条交付通知。' : '供应商提交发货信息后，通知会在此处出现。')
const emptyActionText = computed(() => hasFilters.value ? '清空筛选' : auth.role === 'SUPPLIER' ? '新建通知' : '重新加载')
async function load() { loading.value = true; errorMessage.value = ''; try { const result = await apiList<DeliveryNotice>({ method: 'GET', url: '/delivery-notices' }, mapDelivery, () => demoDeliveries); deliveries.value = result.records } catch (error) { errorMessage.value = extractApiError(error) } finally { loading.value = false } }
function handleEmptyAction() { if (hasFilters.value) { keyword.value = ''; statusFilter.value = '' } else if (auth.role === 'SUPPLIER') openCreate(); else load() }
async function openCreate() { if (auth.role !== 'SUPPLIER') return; try { orders.value = (await apiList<PurchaseOrder>({ method: 'GET', url: '/purchase-orders' }, mapOrder)).records; Object.assign(form, { orderId: '', orderItemId: '', eta: '', quantity: 1, carrierName: '', trackingNo: '', note: '' }); orderItems.value = []; dialogVisible.value = true; if (!eligibleOrders.value.length) ElMessage.info('当前没有已确认、待发货或部分收货订单可创建通知。') } catch (error) { ElMessage.error(extractApiError(error)) } }
async function onOrderChange(orderId: string) { orderItems.value = []; form.orderItemId = ''; if (!orderId) return; try { const raw = await apiRequest<unknown>({ method: 'GET', url: `/purchase-orders/${orderId}` }); const detail = raw && typeof raw === 'object' ? raw as OrderDetail : undefined; orderItems.value = Array.isArray(detail?.items) ? detail.items : []; if (orderItems.value[0]) form.orderItemId = String(orderItems.value[0].id) } catch (error) { ElMessage.error(extractApiError(error)) } }
function showDetail(item: DeliveryNotice) { selected.value = item; ElMessage.info(`${item.noticeNo} 已关联 ${item.orderNo}，详情可在服务端记录中追踪。`) }
async function save() { const valid = await formRef.value?.validate().catch(() => false); if (!valid) return; saving.value = true; try { const payload = { orderId: Number(form.orderId), expectedArrivalAt: `${form.eta}T09:00:00+08:00`, carrierName: form.carrierName || undefined, trackingNo: form.trackingNo || undefined, items: [{ orderItemId: Number(form.orderItemId), quantity: form.quantity }] }; const raw = await apiMutate<unknown>({ method: 'POST', url: '/delivery-notices', data: payload }, () => ({ id: `delivery-demo-${Date.now()}`, noticeNo: `DN-DEMO-${Date.now().toString().slice(-6)}`, supplierName: '当前供应商', orderId: form.orderId, eta: form.eta, quantity: form.quantity, status: 'DRAFT', note: form.note })); const result = mapDelivery(raw); deliveries.value = [result, ...deliveries.value]; dialogVisible.value = false; ElMessage.success('交付通知草稿已创建，请继续提交并发运') } catch (error) { errorMessage.value = extractApiError(error) } finally { saving.value = false } }
async function transitionNotice(item: DeliveryNotice, action: 'SUBMIT' | 'DISPATCH' | 'ARRIVE') { saving.value = true; try { const raw = await apiMutate<unknown>({ method: 'POST', url: `/delivery-notices/${item.id}/actions`, data: { action, expectedVersion: item.version ?? 0, note: action === 'ARRIVE' ? '采购确认到达' : undefined } }, () => ({ ...item, status: action === 'SUBMIT' ? 'SUBMITTED' : action === 'DISPATCH' ? 'IN_TRANSIT' : 'ARRIVED' })); const result = mapDelivery(raw); deliveries.value = deliveries.value.map((entry) => entry.id === result.id ? result : entry); ElMessage.success(action === 'SUBMIT' ? '通知已提交' : action === 'DISPATCH' ? '通知已发运' : '通知已标记到达') } catch (error) { ElMessage.error(extractApiError(error)) } finally { saving.value = false } }
function statusMeta(value: DeliveryNotice['status']) { return ({ DRAFT: { label: '草稿', tone: 'neutral' }, SUBMITTED: { label: '已提交', tone: 'blue' }, IN_TRANSIT: { label: '运输中', tone: 'warning' }, ARRIVED: { label: '已到达', tone: 'success' }, EXCEPTION: { label: '异常', tone: 'danger' }, CANCELLED: { label: '已取消', tone: 'neutral' }, RECEIVED: { label: '已收货', tone: 'success' } } as Record<string, { label: string; tone: 'neutral' | 'warning' | 'success' | 'blue' | 'danger' }>)[value] || { label: value, tone: 'neutral' } }
onMounted(load)
</script>

<style scoped>
.delivery-table { overflow: hidden; }.toolbar-meta { color: var(--lm-muted); font-size: 11px; }.number { font-variant-numeric: tabular-nums; }.form-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 0 14px; }.inline-note { margin-top: 2px; }
@media (max-width: 600px) { .form-grid { grid-template-columns: 1fr; } }
</style>
