<template>
  <div>
    <PageHeader title="采购计划" description="把采购需求聚合为周期计划，经过审批后才能生成采购订单。">
      <template #actions><el-button v-if="auth.role === 'BUYER'" type="primary" :icon="DocumentAdd" @click="openCreate">创建计划</el-button><el-button :icon="Refresh" :loading="loading" @click="load">刷新</el-button></template>
    </PageHeader>
    <section class="surface plan-table">
      <div class="inline-note plan-constraint">V1 约束：一个采购计划只绑定一个供应商，审批后生成一个采购订单；服务端负责校验该关系与幂等性。</div>
      <div class="toolbar"><el-select v-model="statusFilter" clearable placeholder="全部状态" style="width: 155px"><el-option v-for="item in statusOptions" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-input v-model="keyword" clearable placeholder="搜索计划编号或周期" :prefix-icon="Search" /><span class="toolbar-spacer"></span><span class="toolbar-meta">{{ filtered.length }} 个计划</span></div>
      <div v-if="errorMessage" class="inline-error"><WarningFilled />{{ errorMessage }}</div>
      <div v-if="loading && !plans.length" class="table-loading"><div v-for="i in 3" :key="i" class="skeleton" style="height: 47px"></div></div>
      <div v-else-if="!filtered.length"><EmptyState title="暂无采购计划" description="请先准备采购需求，再生成计划草稿。" action-text="查看采购需求" @action="router.push('/purchase-demands')" /></div>
      <div v-else class="table-wrap"><el-table :data="filtered" stripe><el-table-column prop="planNo" label="计划编号" width="170" /><el-table-column prop="period" label="计划周期" width="115" /><el-table-column label="供应商" min-width="165"><template #default="scope">{{ scope.row.supplierName || '需查看计划明细' }}</template></el-table-column><el-table-column label="物料行" width="95" align="right"><template #default="scope"><span class="number">{{ scope.row.lineCount || '—' }}</span></template></el-table-column><el-table-column label="总数量" width="120" align="right"><template #default="scope"><span class="number">{{ scope.row.totalQuantity ? scope.row.totalQuantity.toLocaleString() : '—' }}</span></template></el-table-column><el-table-column label="预计金额" width="145" align="right"><template #default="scope"><span class="number">{{ scope.row.estimatedAmount ? `¥${scope.row.estimatedAmount.toLocaleString('zh-CN', { minimumFractionDigits: 2 })}` : '—' }}</span></template></el-table-column><el-table-column label="状态" width="135"><template #default="scope"><StatusBadge :label="statusMeta(scope.row.status).label" :tone="statusMeta(scope.row.status).tone" /></template></el-table-column><el-table-column prop="owner" label="负责人" width="100" /><el-table-column prop="updatedAt" label="更新时间" width="170" /><el-table-column label="操作" width="250" fixed="right"><template #default="scope"><el-button v-if="scope.row.status === 'DRAFT' && auth.role === 'BUYER'" link type="primary" @click="submitPlan(scope.row)">提交审批</el-button><el-button v-if="scope.row.status === 'PENDING_APPROVAL' && auth.role === 'MANAGER'" link type="primary" @click="approve(scope.row)">批准</el-button><el-button v-if="scope.row.status === 'APPROVED' && auth.role === 'BUYER'" link type="primary" @click="generateOrders(scope.row)">生成订单</el-button><el-button link type="primary" @click="showDetail(scope.row)">查看</el-button></template></el-table-column></el-table></div>
    </section>
    <el-drawer v-model="detailVisible" title="采购计划详情" size="430px"><template v-if="selected"><div class="drawer-title"><div class="drawer-code">{{ selected.planNo }}</div><h2>{{ selected.period }}</h2><StatusBadge :label="statusMeta(selected.status).label" :tone="statusMeta(selected.status).tone" /></div><dl class="drawer-list"><div><dt>供应商</dt><dd>{{ selected.supplierName || '服务端列表未返回，需打开详情接口' }}</dd></div><div><dt>物料行</dt><dd>{{ selected.lineCount ? `${selected.lineCount} 行` : '服务端未返回' }}</dd></div><div><dt>总数量</dt><dd>{{ selected.totalQuantity ? selected.totalQuantity.toLocaleString() : '服务端未返回' }}</dd></div><div><dt>预计金额</dt><dd>{{ selected.estimatedAmount ? `¥${selected.estimatedAmount.toLocaleString('zh-CN', { minimumFractionDigits: 2 })}` : '服务端未返回' }}</dd></div><div><dt>负责人</dt><dd>{{ selected.owner }}</dd></div><div><dt>更新时间</dt><dd>{{ selected.updatedAt }}</dd></div></dl><div v-if="selected.status === 'DRAFT' && auth.role === 'BUYER'" class="drawer-actions"><el-button type="primary" :loading="updating" @click="submitPlan(selected)">提交审批</el-button></div><div v-if="selected.status === 'APPROVED' && auth.role === 'BUYER'" class="inline-note">计划已审批，可以进入采购订单生成流程。订单生成仍需服务端幂等校验。</div><div v-if="selected.status === 'PENDING_APPROVAL' && auth.role === 'MANAGER'" class="drawer-actions"><el-button :loading="updating" @click="reject(selected)">驳回</el-button><el-button type="primary" :loading="updating" @click="approve(selected)">批准计划</el-button></div><div v-if="selected.status === 'APPROVED' && auth.role === 'BUYER'" class="drawer-actions"><el-button type="primary" :loading="updating" @click="generateOrders(selected)">生成订单</el-button></div></template></el-drawer>
    <el-dialog v-model="createVisible" title="创建采购计划" width="560px" destroy-on-close><el-form ref="createFormRef" :model="createForm" :rules="createRules" label-position="top"><el-form-item label="计划名称" prop="planName"><el-input v-model="createForm.planName" placeholder="如 2026-W35 连接器补货" /></el-form-item><div class="form-grid"><el-form-item label="采购需求" prop="demandId"><el-select v-model="createForm.demandId" filterable style="width:100%" placeholder="选择 DRAFT 需求" @change="onDemandChange"><el-option v-for="item in draftDemands" :key="item.id" :label="`${item.demandNo} · ${item.materialName} · ${item.quantity}`" :value="item.id" /></el-select></el-form-item><el-form-item label="供应商" prop="supplierCode"><el-select v-model="createForm.supplierCode" filterable style="width:100%" placeholder="选择一个供应商"><el-option v-for="item in suppliers" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.code" /></el-select></el-form-item><el-form-item label="计划数量" prop="quantity"><el-input-number v-model="createForm.quantity" :min="0.0001" :precision="4" style="width:100%" /></el-form-item><el-form-item label="期望日期" prop="expectedDate"><el-date-picker v-model="createForm.expectedDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item></div><div class="inline-note">创建后为 DRAFT；采购人员提交审批，管理人员批准或驳回。</div></el-form><template #footer><el-button @click="createVisible = false">取消</el-button><el-button type="primary" :loading="creating" @click="createPlan">保存计划</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { DocumentAdd, Refresh, Search, WarningFilled } from '@element-plus/icons-vue'
import { useRouter } from 'vue-router'
import PageHeader from '@/components/PageHeader.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import EmptyState from '@/components/EmptyState.vue'
import { apiList, apiMutate, extractApiError } from '@/services/api'
import { demoPurchasePlans, listResult } from '@/services/demo'
import { mapDemand, mapOrder, mapPlan, mapSupplier } from '@/services/mappers'
import type { PurchaseDemand, PurchaseOrder, PurchasePlan, Supplier } from '@/types'
import { useAuthStore } from '@/stores/auth'

const router = useRouter(); const auth = useAuthStore(); const plans = ref<PurchasePlan[]>([]); const demands = ref<PurchaseDemand[]>([]); const suppliers = ref<Supplier[]>([]); const keyword = ref(''); const statusFilter = ref(''); const loading = ref(false); const updating = ref(false); const creating = ref(false); const errorMessage = ref(''); const selected = ref<PurchasePlan>(); const detailVisible = ref(false); const createVisible = ref(false); const createFormRef = ref<FormInstance>()
const createForm = ref({ planName: '', demandId: '', supplierCode: '', quantity: 0, expectedDate: '' })
const createRules: FormRules = { planName: [{ required: true, message: '请输入计划名称', trigger: 'blur' }], demandId: [{ required: true, message: '请选择采购需求', trigger: 'change' }], supplierCode: [{ required: true, message: '请选择供应商', trigger: 'change' }], quantity: [{ required: true, message: '请输入计划数量', trigger: 'change' }], expectedDate: [{ required: true, message: '请选择期望日期', trigger: 'change' }] }
const statusOptions = [{ value: 'DRAFT', label: '草稿' }, { value: 'PENDING_APPROVAL', label: '待审批' }, { value: 'APPROVED', label: '已批准' }, { value: 'ORDER_CREATED', label: '已生成订单' }, { value: 'REJECTED', label: '已驳回' }, { value: 'CANCELLED', label: '已取消' }]
const filtered = computed(() => plans.value.filter((item) => (!statusFilter.value || item.status === statusFilter.value) && (!keyword.value || `${item.planNo}${item.period}`.toLowerCase().includes(keyword.value.toLowerCase()))))
const draftDemands = computed(() => demands.value.filter((item) => item.status === 'DRAFT'))
async function load() { loading.value = true; errorMessage.value = ''; try { const result = await apiList<PurchasePlan>({ method: 'GET', url: '/purchase-plans' }, mapPlan, () => listResult(demoPurchasePlans).records); plans.value = result.records } catch (error) { errorMessage.value = extractApiError(error) } finally { loading.value = false } }
async function openCreate() { if (auth.role !== 'BUYER') return; try { const [demandResult, supplierResult] = await Promise.all([apiList<PurchaseDemand>({ method: 'GET', url: '/purchase-demands' }, mapDemand), apiList<Supplier>({ method: 'GET', url: '/suppliers' }, mapSupplier)]); demands.value = demandResult.records; suppliers.value = supplierResult.records.filter((item) => item.status === 'ACTIVE'); createForm.value = { planName: '', demandId: '', supplierCode: suppliers.value[0]?.code || '', quantity: 0, expectedDate: '' }; createVisible.value = true; if (!draftDemands.value.length) ElMessage.info('当前没有 DRAFT 采购需求，请先创建需求草稿。') } catch (error) { ElMessage.error(extractApiError(error)) } }
function onDemandChange(id: string) { const item = demands.value.find((entry) => entry.id === id); if (item) { createForm.value.quantity = item.quantity; createForm.value.expectedDate = item.dueDate; if (!createForm.value.planName) createForm.value.planName = `${item.materialName}采购计划` } }
async function createPlan() { const valid = await createFormRef.value?.validate().catch(() => false); if (!valid) return; const item = demands.value.find((entry) => entry.id === createForm.value.demandId); if (!item) return; creating.value = true; try { const raw = await apiMutate<unknown>({ method: 'POST', url: '/purchase-plans', data: { planName: createForm.value.planName, items: [{ demandId: Number(item.id), materialCode: item.materialCode, supplierCode: createForm.value.supplierCode, quantity: createForm.value.quantity, expectedDate: createForm.value.expectedDate }] } }); const result = mapPlan(raw); plans.value = [result, ...plans.value]; createVisible.value = false; ElMessage.success('采购计划草稿已创建，请提交审批') } catch (error) { ElMessage.error(extractApiError(error)) } finally { creating.value = false } }
function showDetail(item: PurchasePlan) { selected.value = item; detailVisible.value = true }
async function submitPlan(item: PurchasePlan) { await updateAction(item, 'SUBMIT', '计划已提交审批') }
async function approve(item: PurchasePlan) { await updateStatus(item, 'APPROVED') }
async function reject(item: PurchasePlan) { await updateStatus(item, 'REJECTED') }
async function updateStatus(item: PurchasePlan, status: PurchasePlan['status']) { updating.value = true; try { const action = status === 'APPROVED' ? 'APPROVE' : 'REJECT'; const raw = await apiMutate<unknown>({ method: 'POST', url: `/purchase-plans/${item.id}/actions`, data: { action, expectedVersion: item.version ?? 0, note: status === 'REJECTED' ? '前端审批驳回' : '前端审批通过' } }, () => ({ ...item, status, updatedAt: new Date().toLocaleString('zh-CN', { hour12: false }) })); const result = mapPlan(raw); plans.value = plans.value.map((entry) => entry.id === result.id ? result : entry); selected.value = result; ElMessage.success(status === 'APPROVED' ? '计划已批准' : '计划已驳回') } catch (error) { ElMessage.error(extractApiError(error)) } finally { updating.value = false } }
async function updateAction(item: PurchasePlan, action: string, message: string) { updating.value = true; try { const raw = await apiMutate<unknown>({ method: 'POST', url: `/purchase-plans/${item.id}/actions`, data: { action, expectedVersion: item.version ?? 0, note: message } }, () => ({ ...item, status: action === 'SUBMIT' ? 'PENDING_APPROVAL' : item.status, updatedAt: new Date().toLocaleString('zh-CN', { hour12: false }) })); const result = mapPlan(raw); plans.value = plans.value.map((entry) => entry.id === result.id ? result : entry); selected.value = result; ElMessage.success(message) } catch (error) { ElMessage.error(extractApiError(error)) } finally { updating.value = false } }
async function generateOrders(item: PurchasePlan) { updating.value = true; try { const raw = await apiMutate<unknown>({ method: 'POST', url: `/purchase-plans/${item.id}/generate-orders`, data: { expectedVersion: item.version ?? 0 } }, () => []); const payload: unknown[] = Array.isArray(raw) ? raw : raw && typeof raw === 'object' && Array.isArray((raw as Record<string, unknown>).items) ? (raw as Record<string, unknown>).items as unknown[] : [raw]; const orders = payload.filter(Boolean).map(mapOrder) as PurchaseOrder[]; ElMessage.success(orders.length ? `已生成 ${orders.length} 笔采购订单` : '订单生成请求已提交'); await load(); router.push('/orders') } catch (error) { ElMessage.error(extractApiError(error)) } finally { updating.value = false } }
function statusMeta(value: PurchasePlan['status']) { return ({ DRAFT: { label: '草稿', tone: 'neutral' }, PENDING_APPROVAL: { label: '待审批', tone: 'warning' }, APPROVED: { label: '已批准', tone: 'success' }, ORDER_CREATED: { label: '已生成订单', tone: 'blue' }, REJECTED: { label: '已驳回', tone: 'danger' }, CANCELLED: { label: '已取消', tone: 'neutral' }, CLOSED: { label: '已关闭', tone: 'neutral' } } as Record<string, { label: string; tone: 'neutral' | 'warning' | 'success' | 'blue' | 'danger' }>)[value] || { label: value, tone: 'neutral' } }
onMounted(load)
</script>

<style scoped>
.plan-table { overflow: hidden; }.plan-constraint { margin: 14px 16px 0; }.toolbar-meta { color: var(--lm-muted); font-size: 11px; }.number { font-variant-numeric: tabular-nums; }.drawer-title { padding-bottom: 18px; border-bottom: 1px solid var(--lm-border); }.drawer-code { color: var(--lm-olive); font-size: 11px; font-weight: 750; }.drawer-title h2 { margin: 8px 0 11px; font-size: 20px; }.drawer-list { margin: 5px 0 0; }.drawer-list > div { display: flex; justify-content: space-between; gap: 20px; padding: 14px 0; border-bottom: 1px solid var(--lm-border); }.drawer-list dt { color: var(--lm-muted); font-size: 12px; }.drawer-list dd { margin: 0; font-size: 12px; font-weight: 650; text-align: right; }.drawer-actions { display: flex; gap: 9px; margin-top: 22px; }.inline-note { margin-top: 20px; }.form-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 0 14px; }
@media (max-width: 600px) { .form-grid { grid-template-columns: 1fr; } }
</style>
