<template>
  <div>
    <PageHeader title="收货" description="对已到达或部分收货订单登记本次实收；服务端事务同步库存、履约进度与库存流水。">
      <template #actions><el-button v-if="auth.role === 'BUYER'" type="primary" :icon="Plus" @click="openCreate">新建收货</el-button><el-button :icon="Refresh" :loading="loading" @click="load">刷新收货</el-button></template>
    </PageHeader>
    <section class="surface receipt-table"><div class="toolbar"><el-input v-model="keyword" clearable placeholder="搜索收货单、订单号或供应商" :prefix-icon="Search" /><el-select v-model="statusFilter" clearable placeholder="全部状态" style="width: 140px"><el-option v-for="item in statusOptions" :key="item.value" :label="item.label" :value="item.value" /></el-select><span class="toolbar-spacer"></span><span class="toolbar-meta">{{ filtered.length }} 笔收货</span></div><div v-if="errorMessage" class="inline-error"><WarningFilled />{{ errorMessage }}</div><div v-if="quantityWarning" class="inline-note receipt-warning"><WarningFilled />{{ quantityWarning }}</div><div v-if="loading && !receipts.length" class="table-loading"><div v-for="i in 3" :key="i" class="skeleton" style="height: 45px"></div></div><div v-else-if="!filtered.length"><EmptyState title="暂无收货记录" :description="emptyDescription" :action-text="emptyActionText" @action="handleEmptyAction" /></div><div v-else class="table-wrap"><el-table :data="filtered" stripe><el-table-column prop="receiptNo" label="收货单号" width="170" /><el-table-column prop="orderNo" label="关联订单" width="170" /><el-table-column prop="supplierName" label="供应商" min-width="180" /><el-table-column prop="receivedAt" label="收货时间" width="170" /><el-table-column label="订单数量" width="112" align="right"><template #default="scope"><span class="number">{{ formatQuantity(scope.row.expectedQuantity, scope.row.quantityLoaded) }}</span></template></el-table-column><el-table-column label="实收数量" width="112" align="right"><template #default="scope"><span class="number">{{ formatQuantity(scope.row.receivedQuantity, scope.row.quantityLoaded) }}</span></template></el-table-column><el-table-column label="差异" width="100" align="right"><template #default="scope"><span class="number" :class="differenceClass(scope.row)">{{ scope.row.quantityLoaded && scope.row.difference > 0 ? '+' : '' }}{{ formatQuantity(scope.row.difference, scope.row.quantityLoaded) }}</span></template></el-table-column><el-table-column label="状态" width="110"><template #default="scope"><StatusBadge :label="statusMeta(scope.row.status).label" :tone="statusMeta(scope.row.status).tone" /></template></el-table-column><el-table-column prop="operator" label="操作人" width="100" /><el-table-column label="操作" width="90" fixed="right"><template #default="scope"><el-button link type="primary" @click="showDetail(scope.row)">查看</el-button></template></el-table-column></el-table></div></section>

    <el-dialog v-model="dialogVisible" title="新建收货" width="560px" destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="form-grid"><el-form-item label="可收货订单" prop="orderId"><el-select v-model="form.orderId" filterable style="width:100%" placeholder="选择已到达或部分收货订单" @change="onOrderChange"><el-option v-for="item in receivableOrders" :key="item.id" :label="`${item.orderNo} · ${item.supplierName}`" :value="item.id" /></el-select></el-form-item><el-form-item label="到货通知" prop="deliveryNoticeId"><el-select v-model="form.deliveryNoticeId" clearable style="width:100%" placeholder="可选；多条已到达通知时必须选择"><el-option v-for="item in deliveryOptions" :key="item.id" :label="item.noticeNo || item.id" :value="item.id" /></el-select></el-form-item><el-form-item label="订单版本" prop="orderVersion"><el-input-number v-model="form.orderVersion" :min="0" :precision="0" controls-position="right" style="width:100%" /></el-form-item><el-form-item label="仓库编码" prop="warehouseCode"><el-select v-model="form.warehouseCode" filterable style="width:100%" placeholder="选择收货仓库"><el-option v-for="item in warehouses" :key="item.id" :label="`${item.warehouseCode} · ${item.warehouseName}`" :value="item.warehouseCode" /></el-select></el-form-item><el-form-item label="订单行" prop="orderItemId"><el-select v-model="form.orderItemId" filterable style="width:100%" placeholder="读取订单详情后选择"><el-option v-for="item in orderItems" :key="String(item.id)" :label="`${item.materialCode || item.materialName || item.id} · 剩余 ${remainingQuantity(item)}`" :value="String(item.id)" /></el-select></el-form-item><el-form-item label="实收时间" prop="receivedAt"><el-date-picker v-model="form.receivedAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%" /></el-form-item><el-form-item label="实收数量" prop="receivedQty"><el-input-number v-model="form.receivedQty" :min="0.0001" :precision="4" style="width:100%" /></el-form-item><el-form-item label="合格数量" prop="qualifiedQty"><el-input-number v-model="form.qualifiedQty" :min="0" :precision="4" style="width:100%" /></el-form-item><el-form-item label="拒收数量" prop="rejectedQty"><el-input-number v-model="form.rejectedQty" :min="0" :precision="4" style="width:100%" /></el-form-item></div><el-form-item label="差异原因"><el-input v-model="form.varianceReason" type="textarea" :rows="2" placeholder="发生短收或拒收时必须填写原因" /></el-form-item><el-form-item label="收货备注"><el-input v-model="form.notes" type="textarea" :rows="2" placeholder="可选" /></el-form-item><div class="inline-note">提交前会校验实收数量、合格/拒收数量与订单版本。拒收数量不计入订单履约完成量，拒收或短收部分仍需后续到货通知与收货补足；重复提交由 Idempotency-Key 防护。</div></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveReceipt">确认收货</el-button></template></el-dialog>
    <el-drawer v-model="detailVisible" title="收货详情" size="430px"><template v-if="selected"><div class="receipt-context"><span>{{ selected.receiptNo }}</span><strong>{{ selected.supplierName || '服务端未返回供应商' }}</strong><small>订单 {{ selected.orderNo }} · {{ selected.receivedAt }}</small></div><dl class="drawer-list"><div><dt>订单数量</dt><dd>{{ formatQuantity(selected.expectedQuantity, selected.quantityLoaded) }}</dd></div><div><dt>实收数量</dt><dd>{{ formatQuantity(selected.receivedQuantity, selected.quantityLoaded) }}</dd></div><div><dt>差异</dt><dd>{{ formatQuantity(selected.difference, selected.quantityLoaded) }}</dd></div><div><dt>状态</dt><dd>{{ statusMeta(selected.status).label }}</dd></div><div><dt>操作人</dt><dd>{{ selected.operator }}</dd></div></dl></template></el-drawer>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { Plus, Refresh, Search, WarningFilled } from '@element-plus/icons-vue'
import PageHeader from '@/components/PageHeader.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import EmptyState from '@/components/EmptyState.vue'
import { useAuthStore } from '@/stores/auth'
import { apiList, apiMutate, apiRequest, extractApiError, isDemoMode } from '@/services/api'
import { demoReceipts } from '@/services/demo'
import { mapDelivery, mapOrder, mapReceipt } from '@/services/mappers'
import type { DeliveryNotice, PurchaseOrder, ReceiptRecord } from '@/types'

interface WarehouseOption { id: string; warehouseCode: string; warehouseName: string }
interface OrderItem { id: string | number; materialCode?: string; materialName?: string; quantity?: number; receivedQty?: number }
interface OrderDetail extends PurchaseOrder { items?: OrderItem[] }
const auth = useAuthStore(); const receipts = ref<ReceiptRecord[]>([]); const orders = ref<PurchaseOrder[]>([]); const deliveries = ref<DeliveryNotice[]>([]); const warehouses = ref<WarehouseOption[]>([]); const orderItems = ref<OrderItem[]>([]); const keyword = ref(''); const statusFilter = ref(''); const loading = ref(false); const saving = ref(false); const errorMessage = ref(''); const quantityWarning = ref(''); const dialogVisible = ref(false); const detailVisible = ref(false); const selected = ref<ReceiptRecord>(); const formRef = ref<FormInstance>()
const form = reactive({ orderId: '', deliveryNoticeId: '', orderVersion: 0, warehouseCode: '', orderItemId: '', receivedQty: 0, qualifiedQty: 0, rejectedQty: 0, varianceReason: '', receivedAt: '', notes: '' }); const rules: FormRules = { orderId: [{ required: true, message: '请选择已到达或部分收货订单', trigger: 'change' }], orderVersion: [{ required: true, message: '请输入订单版本', trigger: 'change' }], warehouseCode: [{ required: true, message: '请选择仓库', trigger: 'change' }], orderItemId: [{ required: true, message: '请选择订单行', trigger: 'change' }], receivedQty: [{ required: true, message: '请输入实收数量', trigger: 'change' }], qualifiedQty: [{ required: true, message: '请输入合格数量', trigger: 'change' }], rejectedQty: [{ required: true, message: '请输入拒收数量', trigger: 'change' }], receivedAt: [{ required: true, message: '请选择实收时间', trigger: 'change' }] }; const statusOptions = [{ value: 'PENDING', label: '待收货' }, { value: 'PARTIAL', label: '部分收货' }, { value: 'COMPLETED', label: '已完成' }, { value: 'DISPUTED', label: '有争议' }]
const receivableOrders = computed(() => orders.value.filter((item) => ['ARRIVED', 'PARTIALLY_RECEIVED'].includes(item.status))); const deliveryOptions = computed(() => { const order = orders.value.find((item) => item.id === form.orderId); return deliveries.value.filter((item) => item.status === 'ARRIVED' && (!form.orderId || item.orderId === form.orderId || (!item.orderId && item.orderNo === order?.orderNo))) }); const filtered = computed(() => receipts.value.filter((item) => (!statusFilter.value || item.status === statusFilter.value) && (!keyword.value || `${item.receiptNo}${item.orderNo}${item.supplierName}`.toLowerCase().includes(keyword.value.toLowerCase()))))
const hasFilters = computed(() => Boolean(keyword.value || statusFilter.value)); const emptyDescription = computed(() => hasFilters.value ? '当前筛选条件下没有匹配记录。' : auth.role === 'BUYER' ? '采购订单到达并选择订单行后，才能提交收货事实。' : '当前可见范围内还没有收货记录。'); const emptyActionText = computed(() => hasFilters.value ? '清空筛选' : auth.role === 'BUYER' ? '创建收货' : '重新加载')
function mapWarehouse(raw: unknown): WarehouseOption { const r = raw && typeof raw === 'object' ? raw as Record<string, unknown> : {}; return { id: String(r.id ?? ''), warehouseCode: String(r.warehouseCode ?? ''), warehouseName: String(r.warehouseName ?? '') } }
async function load() {
  loading.value = true
  errorMessage.value = ''
  quantityWarning.value = ''
  try {
    const result = await apiList<ReceiptRecord>({ method: 'GET', url: '/receipts' }, mapReceipt, () => demoReceipts)
    if (isDemoMode()) {
      receipts.value = result.records
      return
    }
    let detailFailures = 0
    receipts.value = await Promise.all(result.records.map(async (item) => {
      if (item.quantityLoaded || !item.id) return item
      try {
        return mapReceipt(await apiRequest<unknown>({ method: 'GET', url: `/receipts/${item.id}` }))
      } catch {
        detailFailures += 1
        return item
      }
    }))
    if (detailFailures) quantityWarning.value = `${detailFailures} 笔收货详情暂时无法读取，相关数量以“—”显示，未用 0 代替。`
  } catch (error) {
    errorMessage.value = extractApiError(error)
  } finally {
    loading.value = false
  }
}
async function openCreate() { if (auth.role !== 'BUYER') return; try { const [orderResult, deliveryResult, warehouseResult] = await Promise.all([apiList<PurchaseOrder>({ method: 'GET', url: '/purchase-orders' }, mapOrder), apiList<DeliveryNotice>({ method: 'GET', url: '/delivery-notices' }, mapDelivery), apiList<WarehouseOption>({ method: 'GET', url: '/warehouses' }, mapWarehouse)]); orders.value = orderResult.records; deliveries.value = deliveryResult.records; warehouses.value = warehouseResult.records; Object.assign(form, { orderId: '', deliveryNoticeId: '', orderVersion: 0, warehouseCode: warehouses.value[0]?.warehouseCode || '', orderItemId: '', receivedQty: 0, qualifiedQty: 0, rejectedQty: 0, varianceReason: '', receivedAt: new Date().toISOString().slice(0, 19), notes: '' }); orderItems.value = []; dialogVisible.value = true; if (!receivableOrders.value.length) ElMessage.info('当前没有已到达或部分收货订单可继续收货。') } catch (error) { ElMessage.error(extractApiError(error)) } }
async function onOrderChange(orderId: string) { const item = orders.value.find((entry) => entry.id === orderId); form.orderVersion = item?.version ?? 0; form.deliveryNoticeId = ''; orderItems.value = []; if (!orderId) return; try { const raw = await apiRequest<unknown>({ method: 'GET', url: `/purchase-orders/${orderId}` }); const detail = raw && typeof raw === 'object' ? raw as OrderDetail : undefined; orderItems.value = Array.isArray(detail?.items) ? detail.items.filter((entry) => remainingQuantity(entry) > 0) : [] } catch (error) { ElMessage.error(extractApiError(error)) } }
async function saveReceipt() { const valid = await formRef.value?.validate().catch(() => false); if (!valid) return; if (Math.abs(form.receivedQty - form.qualifiedQty - form.rejectedQty) > 0.0001) { ElMessage.error('实收数量必须等于合格数量与拒收数量之和'); return } if (form.rejectedQty > 0 && !form.varianceReason.trim()) { ElMessage.error('存在拒收数量时必须填写差异原因'); return } saving.value = true; try { const raw = await apiMutate<unknown>({ method: 'POST', url: '/receipts', data: { orderId: Number(form.orderId), deliveryNoticeId: form.deliveryNoticeId ? Number(form.deliveryNoticeId) : undefined, orderVersion: form.orderVersion, warehouseCode: form.warehouseCode, receivedAt: `${form.receivedAt}+08:00`, notes: form.notes, items: [{ orderItemId: Number(form.orderItemId), receivedQty: form.receivedQty, qualifiedQty: form.qualifiedQty, rejectedQty: form.rejectedQty, varianceReason: form.varianceReason || undefined }] } }); const result = mapReceipt(raw); receipts.value = [result, ...receipts.value]; dialogVisible.value = false; ElMessage.success('收货已提交，库存与订单履约进度已由服务端更新'); await load() } catch (error) { ElMessage.error(extractApiError(error)) } finally { saving.value = false } }
function showDetail(item: ReceiptRecord) { selected.value = item; detailVisible.value = true }
function handleEmptyAction() { if (hasFilters.value) { keyword.value = ''; statusFilter.value = '' } else if (auth.role === 'BUYER') openCreate(); else load() }
function formatQuantity(value: number, loaded = true) { return loaded ? value.toLocaleString('zh-CN') : '—' }
function remainingQuantity(item: OrderItem) { return Math.max(Number(item.quantity || 0) - Number(item.receivedQty || 0), 0) }
function differenceClass(item: ReceiptRecord) { return !item.quantityLoaded ? '' : item.difference < 0 ? 'danger-number' : item.difference > 0 ? 'warning-number' : 'safe-number' }
function statusMeta(value: ReceiptRecord['status']) { return ({ PENDING: { label: '待收货', tone: 'warning' }, PARTIAL: { label: '部分收货', tone: 'warning' }, COMPLETED: { label: '已完成', tone: 'success' }, DISPUTED: { label: '有争议', tone: 'danger' } } as Record<string, { label: string; tone: 'neutral' | 'warning' | 'success' | 'blue' | 'danger' }>)[value] || { label: value, tone: 'neutral' } }
onMounted(load)
</script>

<style scoped>
.receipt-table { overflow: hidden; }.toolbar-meta { color: var(--lm-muted); font-size: 11px; }.number { font-variant-numeric: tabular-nums; }.danger-number { color: var(--lm-danger); }.warning-number { color: var(--lm-warning); }.safe-number { color: var(--lm-success); }.receipt-context { display: grid; gap: 5px; margin-bottom: 20px; padding: 13px 14px; border-left: 3px solid var(--lm-olive); background: var(--lm-surface); }.receipt-context span { color: var(--lm-olive); font-size: 11px; font-weight: 750; }.receipt-context strong { font-size: 15px; }.receipt-context small { color: var(--lm-muted); font-size: 11px; }.form-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 0 14px; }.drawer-list { margin: 0; }.drawer-list > div { display: flex; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid var(--lm-border); }.drawer-list dt { color: var(--lm-muted); font-size: 12px; }.drawer-list dd { margin: 0; font-size: 12px; font-weight: 650; }.inline-note { margin-top: 3px; }.receipt-warning { display: flex; align-items: center; gap: 7px; margin: 0; border-width: 0 0 1px; }.receipt-warning svg { width: 14px; flex: 0 0 auto; }
@media (max-width: 600px) { .form-grid { grid-template-columns: 1fr; } }
</style>
